services:
  - type: web
    name: waga-sklepowa-ai
    env: python
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
